apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-to-argo-app-{{ template "cluster_name" . }}
  namespace: yoav-web
spec:
  destination:
    namespace: yoav-web
    server: https://api.restore-test.cloudlet-dev.com:6443
  project: default
  source:
    path: .
    repoURL: https://github.com/DavidDaskalo/argo-example-app.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
