apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-to-argo-app-{{ template "cluster_name" . }}
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: .
    repoURL: https://github.com/DavidDaskalo/argo-example-app.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
